# Generated by Django 5.1.1 on 2024-12-29 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Viewer'), (2, 'Editor'), (3, 'Admin')], default=1),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('tasks', models.TextField(blank=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='event_files/')),
                ('organizers', models.ManyToManyField(blank=True, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
