# Generated by Django 5.1.1 on 2024-12-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_parent_project'),
        ('user_account', '0003_alter_event_participants_alter_event_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='events', to='project.project'),
        ),
    ]
