# Generated by Django 5.1.1 on 2024-11-23 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_projects', to='project.project', verbose_name='Родительский проект'),
        ),
    ]
